services:
  db:
    image: mysql:latest
    restart: always
    container_name: daily-diet-mysql
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'daily-diet'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3307:3306"
    volumes:
      - daily_diet_mysql_data:/var/lib/mysql

volumes:
  daily_diet_mysql_data: